version: 2.1
commands:
   destroy_env:
     steps:
       - run:
           command: |
             aws cloudformation delete-stack \
               --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}

jobs:
  configuration_infra:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["06:ee:36:6f:f0:b9:22:f7:e3:7c:d0:f6:3b:14:57:d6"]
      - run:
          command: |
            apk add --update ansible
      - run:
          command: |
            ansible-playbook -i hosts main-remote.yml
  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run:
          command: |
            apk add --update curl
      - run: |
            curl -I http://3.82.251.52:3000
      - destroy_env:
        when: on_fail
workflows:
  workflows:
    jobs:
      - configuration_infra
      - smoke_test:
          requires: [configuration_infra]